### ISSUE TITLE
meal-personnel-prediction repo fork 사용자분들께

### ISSUE THREAD

**Issue by heehehe** [heehehe/meal-personnel-prediction-alert#1]
@1jimin3 @jiyeoneom1 
~@yosepyun @jonhyuk0922 @dodorip @OKHYUNJONG @woo1 @bemrung2 @Daehyuk8756 @soohyunme~ 

안녕하세요, 기존 meal-personnel-prediction repo 소유자입니다.

제가 몇년 전 다른 팀원분들과 진행했던 프로젝트와 동일한 주제로 dacon에서 대회가 개최된 것을 알게 되었습니다.
이전에 github에 코드 및 파일을 업로드 해놓은 사실을 간과하고 있다가, 
많은 분들이 fork해가시는 것과 dacon에 해당 repo가 공유되어 있는 것을 확인했습니다.

죄송하지만, fork해가신 repo는 **private으로 변경 및 삭제** 부탁드립니다.
(<kbd>Settings</kbd> 내 하단에서 Change visibility 및 Delete this repository 를 통해 가능하십니다.)
![image](https://user-images.githubusercontent.com/41580746/123746134-2f288c00-d8ec-11eb-84f8-0166a79b24ad.png)

또한 repo 내 파일은 공유 및 dacon 대회에서 **사용을 금지**해주시길 당부드립니다.

모든 분의 이메일이 공개되어 있지 않아, 이렇게 issue로 말씀드리는 점 양해 부탁드립니다.

**private 처리 완료 후 해당 issue에 코멘트** 부탁드립니다.
번거롭게 해드려 죄송합니다.

**Comment by bemrung2** [comment]
[image: issue.JPG]

안녕하세요.

Delete repo 후 증빙 사진과 함께 메일 보내드립니다.

더 해야할 조치가 있으면 답장 부탁드립니다.

감사합니다.

2021년 6월 29일 (화) 오후 3:39, Heeseon Cheon ***@***.***>님이 작성:

**Comment by heehehe** [comment]
@bemrung2 님 빠른 대응 감사드립니다!

**Comment by soohyunme** [comment]
안녕하세요.

삭제 완료했습니다.

**Comment by heehehe** [comment]
@soohyunme 님 빠르게 처리해주셔서 감사합니다!

**Comment by Daehyuk8756** [comment]
안녕하십니까,

삭제 완료하였습니다. 확인 부탁드립니다:)

감사합니다.

iOS용 Outlook<https://aka.ms/o0ukef> 다운로드
________________________________
보낸 사람: Heeseon Cheon ***@***.***>
보낸 날짜: Tuesday, June 29, 2021 3:49:39 PM
받는 사람: heehehe/meal-personnel-prediction-alert ***@***.***>
참조: (학생) 부대혁 (경영학부) ***@***.***>; Mention ***@***.***>
제목: Re: [heehehe/meal-personnel-prediction-alert] meal-personnel-prediction repo fork 사용자분들께 (#1)


@soohyunme<https://github.com/soohyunme> 님 빠르게 처리해주셔서 감사합니다!

**Comment by heehehe** [comment]
@Daehyuk8756 님 확인 완료했습니다. 감사합니다!

**Comment by woo1** [comment]
삭제 완료했습니다.

**Comment by OKHYUNJONG** [comment]
대회에서 어떤분이 깃허브 링크를 올려주셔서 참고용으로 본 것이고 코드나 소스를 전혀 활용하지 않았습니다.(그 대회를 참여한 것도
아니고요) Fork 해둔것은 지웠습니다

2021년 6월 29일 (화) 오후 3:39, Heeseon Cheon ***@***.***>님이 작성:

**Comment by heehehe** [comment]
@woo1 @OKHYUNJONG 감사드립니다!

**Comment by dodorip** [comment]
안녕하세요
삭제 완료했습니다. 해당 데이터를 활용하여 해당 대회에 참여하지는 않았습니다.
감사합니다

**Comment by heehehe** [comment]
@dodorip 감사합니다:)

**Comment by jonhyuk0922** [comment]
안녕하세요! 삭제 완료하였습니다!

**Comment by heehehe** [comment]
@jonhyuk0922 감사합니다!!

**Comment by yosepyun** [comment]
안녕하세요 삭제 완료했습니다.

**Comment by heehehe** [comment]
@yosepyun 감사드립니다!
